const { chromium } = require('playwright')
const path = require('path')
;(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  page.on('console', (m) => console.log(`[console.${m.type()}]`, m.text()))
  page.on('pageerror', (e) => console.log('[pageerror]', e.stack || e.message))
  page.on('requestfailed', (r) => console.log('[404/fail]', r.url(), r.failure()?.errorText))
  page.on('response', (r) => { if (r.status() >= 400) console.log('[http', r.status() + ']', r.url()) })
  await page.goto('http://localhost:3001/', { waitUntil: 'networkidle', timeout: 60000 })
  await page.waitForTimeout(12000)
  const pct = await page.evaluate(() => document.body.innerText.match(/(\d+)\s*%/)?.[1] ?? '?')
  console.log('loading pct after wait:', pct)
  await browser.close()
})()
